# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rahul-thakoor.github.io/
baseurl: 
title: Rahul Thakoor
author: Rahul Thakoor
description: Personal blog and resume
avatar: profile.JPG
email: rahul27@qq.com
github: rahul-thakoor # username
twitter: 
linkedin: 
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: username
google_analytics: 


# needed for travis-ci build
exclude: [vendor]
