# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rahul-thakoor.github.io/
baseurl: 
title: Rahul
author: Rahul
description: Personal blog
avatar: profile.png
email: rahul27@qq.com
github: rahul-thakoor # username
twitter: 
linkedin: 
stackoverflow: 
#Comment out if you don't want disqus 
disqus: rahulthakoor
#google_analytics: 


# needed for travis-ci build
exclude: [vendor]
